export const developerData = {
    name: "Sujay Mukherjee",
    nickname: "Sujay",
    occupation: "Full-Stack Web & Software Developer",
    aboutPageOnlyOccupation: "Web & Software Developer",
    location: "West Bengal, India",
    email: "sujay-mukherjee@outlook.com",
    otherEmailAddresses: ["developer.sujay19@gmail.com", "sujay.mukherjeedev@gmail.com"],
    github: "https://github.com/devsujay19",
    twitter: "https://twitter.com/devsujay19",
    googleDeveloperProfile: "https://g.dev/devsujay19",
    youtube: "https://youtube.com/@Sujay_Mukherjee",
    threads: "https://threads.net/devsujay19",
    instagram: "https://instagram.com/devsujay19",
    facebook: "https://facebook.com/people/Sujay-Mukherjee/100092647425033",
};